CREATE TABLE USER
(
    UID INT PRIMARY KEY,
    DSA_PRIVATE_KEY VARBINARY(1024),
    DSA_PUBLIC_KEY VARBINARY(1024),
    RSA_PRIVATE_KEY VARBINARY(2048),
    RSA_PUBLIC_KEY VARBINARY(512),
    EMAIL VARCHAR(255),
    HASHED_PASSWORD VARCHAR(255),
    SALT VARBINARY(16),
    USER_ENCRYPTION_KEY VARBINARY(64),
    USER_MASTER_KEY VARBINARY(64),
    USERNAME VARCHAR(255) UNIQUE,
    VERIFIED BOOLEAN
);

CREATE TABLE UPLOADED_FILE
(
    FID INT PRIMARY KEY,
    ENCRYPTED BOOLEAN,
    FILENAME VARCHAR(255),
    IDENTIFIER VARCHAR(255),
    SIGNATURE VARBINARY(256),
    SIGNATURE_TYPE SMALLINT,
    UPLOAD_TIME TIMESTAMP
);

CREATE TABLE USER_UPLOADED_FILES
(
    USER_UID INT,
    UPLOADED_FILES_FID INT,
    PRIMARY KEY(USER_UID, UPLOADED_FILES_FID),
    FOREIGN KEY(USER_UID) REFERENCES USER(UID),
    FOREIGN KEY(UPLOADED_FILES_FID) REFERENCES UPLOADED_FILE(FID)
);

CREATE TABLE SESSION
(
    USER_UID INT,
    SESSION_ID VARCHAR(255),
    VALID_THROUGH TIMESTAMP,
    PRIMARY KEY(USER_UID),
    FOREIGN KEY(USER_UID) REFERENCES USER(UID)
);

CREATE TABLE RESET_PASSWORD_TOKEN
(
    USER_UID INT,
    TOKEN VARCHAR(255),
    VALID_THROUGH TIMESTAMP,
    PRIMARY KEY(USER_UID),
    FOREIGN KEY(USER_UID) REFERENCES USER(UID)
);

CREATE TABLE VERIFICATION_TOKEN
(
    USER_UID INT,
    TOKEN VARCHAR(255),
    VALID_THROUGH TIMESTAMP,
    PRIMARY KEY(USER_UID),
    FOREIGN KEY(USER_UID) REFERENCES USER(UID)
);


